version: '3'

services:
  mysql:
    image: mysql:8.0.21
    container_name: mysql
    platform: linux/x86_64
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=123456
    restart: 'always'
    volumes:
      - ./srv/db
    networks:
      - project-verzel
networks:
  project-verzel:
    name: project-verzel