version: '3'

services:
  mysql:
    image: mysql:8.0.21
    container_name: mysql
    platform: linux/x86_64
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=123456
    restart: 'always'
    volumes:
      - ./srv/db
    networks:
      - project-verzel

  frontend:
    build: ./front-end
    container_name: front-end_verzel
    working_dir: /srv/front-end
    ports:
      - 5173:5173
    restart: always
    environment:
      - VITE_APP_BACK_END_URL=http://localhost:5180
      - PORT_FRONT=5173
    # command: bash -c 'npm i && npm run dev'
    networks:
      - project-verzel
    volumes:
      - ./front-end/src:/srv/front-end/src
    depends_on:
      - backend

  backend:
    container_name: back-end_verzel
    build: ./back-end
    restart: always
    working_dir: /srv/back-end
    environment:
      - DATABASE_URL=mysql://root:123456@mysql:3306/verzel?schema=public
      - PORT=5180
      - JWT_KEY=teste123
    ports:
      - 5180:5180
    volumes:
      - ./back-end:/srv/back-end
    networks:
      - project-verzel
    depends_on:
      - mysql

  # storage:
  #   container_name: storage_verzel
  #   build: ./storage
  #   restart: always
  #   working_dir: /srv/storage
  #   networks:
  #     - project-verzel

networks:
  project-verzel:
    name: project-verzel
