version: '3'

services:
  frontend:
    build: ./front-end
    container_name: front-end_verzel
    working_dir: /srv/front-end
    env_file: .env
    ports:
      - '${PORT_FRONT}:${PORT_FRONT}'
    restart: always
    networks:
      - project-verzel
    depends_on:
      - backend

  backend:
    container_name: back-end_verzel
    build: ./back-end
    restart: always
    working_dir: /srv/back-end
    env_file:
      - .env
    ports:
      - '${PORT_BACK}:${PORT_BACK}'
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "lsof", "-t", "-i:5180"]
      timeout: 10s
      retries: 5
    networks:
      - project-verzel

  db:
    image: mysql:8.0.21
    container_name: db
    platform: linux/x86_64
    ports:
      - 3506:3306
    environment:
      - MYSQL_ROOT_PASSWORD=123456
    restart: 'always'
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 10s
      retries: 5
    # depends_on:
    #   - storage

  # storage:
  #   container_name: storage_verzel
  #   build: ./storage
  #   restart: always
  #   working_dir: /srv/storage
  #   networks:
  #     - project-verzel

networks:
  project-verzel:
    name: project-verzel
