version: '3'

services:
  mysql:
    image: mysql:8.0.21
    container_name: mysql
    platform: linux/x86_64
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=123456
    restart: 'always'

  # frontend:
  #   build: ./front-end
  #   container_name: front-end_verzel
  #   working_dir: /srv/front-end
  #   ports:
  #     - 5173:5173
  #   restart: always
  #   networks:
  #     - project-verzel
  #   depends_on:
  #     - backend

  # backend:
  #   container_name: back-end_verzel
  #   build: ./back-end
  #   restart: always
  #   working_dir: /srv/back-end

  #   ports:
  #     - 5180:5180
  #   networks:
  #     - project-verzel
  #   depends_on:
  #     - mysql

  # storage:
  #   container_name: storage_verzel
  #   build: ./storage
  #   restart: always
  #   working_dir: /srv/storage
  #   networks:
  #     - project-verzel

networks:
  project-verzel:
    name: project-verzel
